Tests
zakharoff/edit-book pull request #3
Opened 2020-11-27 01:49 UTC by romka69

2020-11-28 14:11 UTC, indevelope requested changes

2020-11-28 14:11 UTC, indevelope commented on src/mocks/handlers.js
> +export const handlers = [
здесь похоже не хватает метода для chapters. Так как у меня тест проваливается на 
<img width="850" alt="shot" src="https://user-images.githubusercontent.com/24797895/100517239-0c45c600-31ab-11eb-8bdc-2b10f04731d4.png">

2020-11-28 14:11 UTC, indevelope commented on package.json
> +    "gatsby-plugin-mdx": "^1.5.0",
выглядит что этот плагин здесь лишний

2020-11-28 14:11 UTC, indevelope commented on README.md
> +![](https://i.imgur.com/Dvma2PF.png)
На этой строчке парсеру docz несколько плохеет. Чтобы это подлечить придётся прибегнуть к https://www.gatsbyjs.com/docs/working-with-images-in-markdown/#using-the-mdx-plugin но я в таких случаях рекомендовал бы не копаться в конфигурации к docz, а просто исключить readme.md из документации и добавить отдельный mdx, вставляя картинку в mdx.

2020-11-30 09:44 UTC, index01d approved these changes

2020-11-30 11:53 UTC, merged